### ISSUE TITLE
Can't add people on iPad with keyboard

### ISSUE THREAD

**Issue by sebsel** [janderk2/hetongeluk#3]
_Ik zie dat je deze in het Engels doet..._

I was trying to add an article on my iPad, but adding people does not seem to work there. Without adding people, I can't submit the article, so I had to switch to my laptop.

After submitting I had some more debugging:
- it works on my iPhone, so that's weird.
- when I unplug the keyboard to my iPad it works again.

I think this is because of the use of `<span>` and `onclick`. When there is no keyboard connected, iPad will be compatible and fire onclicks for tabs. But when the keyboard is connected, some keyboards will have a mouse, so it will probably distinguish between onclick and ontab. (Mine has no mouse, but it seems like it still distinguishes.)

One could think the bug is with Apple, but the better way is not to use a `<span>` when you want to use it to click on. The accessible option would be to use a `<input type="radio">`, which does what you want out of the box, plus has advantages for screenreaders and different devices :)

**Comment by janderk2** [comment]
Do you mean you can't even tab it? I use onclicks on div's and span's pretty much everywhere. Haven't seen a problem on any platforms. One would expect to see the problem at many other places. Is it only on the "Add Humans" span button?

Also can't test it as I do have an iPad but only without a keyboard.

**Comment by janderk2** [comment]
Also the code is in English as hetongeluk.nl is going international soon. Check out thecrashes.org. Also Dutch is not the most spoken language among programmers.

**Comment by sebsel** [comment]
I did look around a bit and you are right: most of them are `<div>` with onclick, or other block-elements. The counter example is the button with ‘Mensen toevoegen’ / ‘Add people’, which is a `<span>` as well, and that button works on iPad. My second thought was that it had to do with the hover state (when I tab the buttons, they change to their hover state), but other buttons seem to have a hover state as well.

So, I will have to dig deeper to find the cause.

In general, I think you will have fewer of these kinds of bugs when writing semantic HTML. So: when you want a button, use `<button>` and not `<span onclick>`. It’s easier for browsers to adapt to what you mean if you tell them what you mean, instead of what they should do. But I can’t really prove that is the problem here.

I’ll try to come back to this when I got more time.

**Comment by janderk2** [comment]
span or div should not make any difference. Both are used a lot (also on this github page) in combination with onclick events. 

What I did do is update the Add Humans button with a role="button" attribute and change the span into a div. That should hint that it is a button. Would appreciate if you could check if this makes on your ipad with keyboard.

**Comment by sebsel** [comment]
Sorry for the late reply. I have checked it now.

Yes, I am able to select people now, on my iPad with the keyboard selected!

While testing, I was a bit confused that when I select 'Injury' or 'Characteristics' first, and _then_ 'Transportation mode', the first two will not be selected anymore. This, however, seems totally unrelated to this issue, so closing it :)
